#!/usr/bin/python3
import sys
import requests

# ======= Variables =======
URL = ""

# ======= Functions =======
def usage():
    print("usage: ./dir-scanner [URL] [OPTIONS]...[ -h | -w ]\n" + 
          "options:\n" + 
          "\t-w : Wordlist\n")
    exit(0)

def error(c):
    print("Error: " + c)
    exit(-1)

def forward_slash(url):
    url = list(url)
    if (url[-1] == '/'):
        return "".join(url)
    return "".join(url) + "/"


# ======= Main =======

argv = sys.argv
if (len(argv) < 3):
    usage()

# Check for backslash
URL = forward_slash(argv[3])

# Wordlist index
wordlist_index = argv.index('-w') + 1
wordlist = argv[wordlist_index]

for word in open(wordlist,'r'):
    print(URL + word)
    r = requests.get(URL + word)
